### ISSUE TITLE
Game Over Screen

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#10]
Gonna prototype up a Game Over screen, basically a new `<section>` that will take the place of `#ScoreSheet`

Ideas of stuff to display:
1 **The Wrongest Words**
  The single card that received the worst score all game. Might need some finangling as this could frequently be a tie, but I think this could be a really fun parting shot.
2. Final Scores
3. "Play Again" link (is this possible?)
4. Link to submit bugs.
5. Link to submit wrong statements

**Comment by AhoyLemon** [comment]
Okay, commit [6fb367f] really put together a first sketch of what I was thinking here. I'm pleased with how this turned out.

So, `#GameOverScreen` has been added, and the first thing is the actual Wrongest Words. I'm hoping this data is available, and at this exact moment, I'm thinking the computer can just pick one at random if there's a tie? I'll probably have to revisit that and come up with a better solution, but I really like being able to just display "This is the dumbest statement of the night". If that's possible to build, that would be tits.

Under that is the final scores, ordered by place.

Then I have a Play again button. I'm not sure if that's a pain in the ass to clear out the data for a new round or not. If it is, that button could genuinely be a javscript refresh button and serve basically the same effect.

And then some text links.

So I'm obviously using the classes for styles, but those IDs were just what made sense at the time. If you need to add/change/remove any IDs from anywhere in that section, that's totally fine I'm not using them for anything.

And that's generally my concept. Fake data is in there currently, and I have a debug link on the setup screen just to take you to the game over screen while this is being worked out.

Tossing it over to ya.

**Comment by AnotherDole** [comment]
This looks great. The only thing I'm not sure about is whose name goes in the cite under the blockquote. I thought it would be the author of the quote but in #14 you mentioned that we might not want to use that information anymore.

**Comment by AnotherDole** [comment]
Oops, e0e493de88f8831eaabc0f90d22389d3ad69873d is actually for this issue. Anyway, it displays the right data when the game is over. Restarting the game is definitely possible, but it's not completely implemented yet.

**Comment by AhoyLemon** [comment]
Yeah, I see your point.

I think the `<cite>` has to go to the player who defended that statement. Referencing the person who said it initially is one option, but A.) there will be situations in the future where the quote is unsourced and B.) that's not as fun of a reveal to the players. The way it's set up, the game ends and everyone sees.
> Having sex with goats is way more fun than having sex with people.
> <cite>&#8213; Dole</cite>

Which I think taps into the enjoyment of the game.

**Comment by AnotherDole** [comment]
Multiple people can have the same card over the course of a game. Should it show everyone who had that card or just the last person who defended it?

Either way, it will take some changes to the server that I don't want to make yet.

**Comment by AhoyLemon** [comment]
Yeah, I think that's fun. Right?
> Having sex with goats is way more fun than having sex with people.
> <cite>&#8213; Dole & Lemon</cite>
