### ISSUE TITLE
Try a new "copy/paste" idea.

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#11]
The current one works terrific for a desktop, but when you're on a phone, the input text is selected, but you don't get the "copy" button in the dashboard.

I think if I go focus, select, focus again, that might force the mobile browser to recognize what I'm trying to do here.

**Comment by AhoyLemon** [comment]
This is trickier than I imagined. I think what I just built here is about as good as it's gonna be.

**Comment by samuwen** [comment]
I feel like this should just default to having the text auto-focus. Alternately you can create a modal with the selected text?

**Comment by AhoyLemon** [comment]
Opening this back up, because what I currently have up there just isn't gonna work for phones, maybe I need to try something dumbed down, a text input without js, and you and your browser can figure it out from there.
