### ISSUE TITLE
Pretty up error.html

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#12]
Currently, error.html comes up if you have a URL shortcode that doesn't have a room associated with it. 

While it doesn't need to do much, it should get a little bit of design to it.

**Comment by AnotherDole** [comment]
The behavior of redirecting to error.html isn't set in stone. It was just the first thing I could think of when I was writing that part of the code.

**Comment by AhoyLemon** [comment]
Is there something else you'd like to do instead?

I guess if we handled it in a `<section>` inside of index.html, that probably makes more sense.

**Comment by AnotherDole** [comment]
That could work too. Adding a separate page for it was just the simplest solution at the time.

**Comment by AhoyLemon** [comment]
I feel like a new `<section>` is probably the appropriate way to go. That way we don't have to build new CSS and JS and we can direct people to the correct place.

**Comment by AhoyLemon** [comment]
So I saw a commit saying this now happens in a toast? So this guy is closable?

**Comment by AnotherDole** [comment]
No, I haven't done anything related to this.

**Comment by AnotherDole** [comment]
Did this with a toast. Kind of an ugly solution codewise but it works.

**Comment by AhoyLemon** [comment]
Works for me!
