### ISSUE TITLE
Separating .js from .html

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#13]
Do you mind if we start turning all this javascript stuff into .js files? I feel like index.html is a lot messier than it needs to be.

I think there's probably 3 files here.

1. `functions.js` for multiuse stuff and anything that starts with functon.
2. `sockets.js` for anything that starts with socket
3. `actions.js`, for stuff like `$('button').click(`, or pretty much anything that gets fired on load. I actually have an actions.js file already, but it doesn't have much in there.

I usually use [Prepros](https://prepros.io/) to concatonate my javascript (same as with all the Sass > CSS), but since I don't think that's part of your workflow, we can just include those files at the bottom. under the jQuery and whatever.

Whatcha think?

**Comment by AnotherDole** [comment]
Yes, this definitely needs to be done at some point. Let me finish up Issue #3 and then I'll let you separate the javascript how you want.

**Comment by AhoyLemon** [comment]
Works for me. I'm playing around with Issue #10 right now.

**Comment by AhoyLemon** [comment]
Well, #3 is closed, so I'm gonna try to split these up now.

**Comment by AhoyLemon** [comment]
Okay, I did what I said I'd do, and tested the results a couple times, and I'm *pretty sure* it's running good.

Regardless, I'd like to to take a look at it as well to see if something jumps out at you, since you've written more of that javascript as well. Also if you had a good idea of what to do with the stuff I kept in the script block.

**Comment by AnotherDole** [comment]
I think this will work for now.
