### ISSUE TITLE
Cleaning up some unnecessary things

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#14]
There's a couple of things that I've noticed aren't being used and I'm wondering if they will be used in the future or should be removed.

1. Every time someone votes, the server sends a message to everyone in the room saying who voted for which statements. 
2. Every statement has an associated author and source but right now these aren't displayed anywhere.

**Comment by AhoyLemon** [comment]
As for your second point, I'm wondering if maybe that additional syntax should go? Here's why.

Right now we've got quote, author, episode, but that just sort of made sense at the prototyping stage when we didn't have much info. Pretty soon here we can get this thing released and in public hands at which point it would be great to throw decks together on a whim and not be tied into actually sourcing only F Plus quotes.

I think down the road there will be one or two F Plus decks, and then a bunch of other decks not F Plus related.

Which is a lot of words to say I don't think the other pieces of information are of great use, and I think if the structure is as it is, that might hamper the creation of other decks.

**Comment by AhoyLemon** [comment]
As for the first thing, I can't think of what I could do with that information. Where's this message going? If it's console.log, then it hardly matters, but I can definitely see just wanting to clean out the crap that isn't getting used.
