### ISSUE TITLE
Showing that a statement is worth more points

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#15]
Players earn double points for successfully defending a statement that was previously voted as wrong, but there is no indication of when a statement is worth more. I think there should be some indication to the player that is defending a statement that is worth more.

**Comment by AhoyLemon** [comment]
Yeah, that's a great idea. I'm trying to think of a way to visually indicate that. I'm thinking maybe just a little icon.... Like... if I make an svg that's like a construction hat or a nutcup or trigonometry or something?

I'll try to sketch something and stick it on there to see if it works.

**Comment by AhoyLemon** [comment]
First try:
![this one is hard](http://hirelemon.com/junk/hard1.svg)

**Comment by AhoyLemon** [comment]
I like this one a lot better.
![Gordian Knot Means HARD!](http://hirelemon.com/junk/hard2.svg)

**Comment by AhoyLemon** [comment]
New commit adds the symbol above to the card front. `img.this-is-hard` goes inside of `.front .inner`, just before the `blockquote`

**Comment by AnotherDole** [comment]
Looks good. If the statement is really long, though, the sticker overlaps a little with the words.

**Comment by AhoyLemon** [comment]
Sure does. Also as I looked at that, I realized that the "I'm done early" button actually fucks up the vertical centering, so the quote doesn't vertically align as it should. Absolute positioned the done early button and played with some more classes, I think this looks a lot better.
