### ISSUE TITLE
Explore alternatives to flipclock.js

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#18]
The more I look at flipclock, the less I like it. It's probably worth doing a little bit of research and thinking and see if we can't have a cleaner clock design in there instead.

**Comment by AhoyLemon** [comment]
Oooh! I like this!
[jQuery Knob](http://anthonyterrien.com/knob/)

I'm gonna play around with trying to make this in a timer in CodePen. If it works, I'm doing it, cause that looks rad.

**Comment by AhoyLemon** [comment]
There we go, I made this.
[http://codepen.io/ahoylemon/pen/PwVNmO](http://codepen.io/ahoylemon/pen/PwVNmO)

Gonna try to implement it in the game.

**Comment by AnotherDole** [comment]
Ooh, very nice. I like it better than the flipclock.

**Comment by AhoyLemon** [comment]
Oh, is the flipclock tied to the game settings now? Is that solved?

**Comment by AnotherDole** [comment]
Yes.

**Comment by AhoyLemon** [comment]
Awesome. Working on a tiny knob for the next round timer, then I'll close this.
