### ISSUE TITLE
Quote submission

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#24]
[Here's] (https://docs.google.com/spreadsheets/d/1IsbE1CepNrXBPSOqfZRntBHt3wlq9qCPGQZA0rEqE08/edit#gid=0) the link to the spreadsheet you couldn't find.

It would be nice to have a more formal way of submitting quotes.

**Comment by AhoyLemon** [comment]
Yeah, that's something we gotta come up with. I think probably something using a similar i/o workflow as the [F Plus Issues page](http://thefpl.us/issues) where you submit your things using a google form, that populates a google spreadsheet, and that spreadsheet is loaded into the DOM via ajax.

I think that'll work okay, unless there's another option.

**Comment by AhoyLemon** [comment]
[Made a Google Form](http://goo.gl/forms/vGhjsQyIxS)

What do you think?

**Comment by AnotherDole** [comment]
I like it and I just submitted one as a test.

**Comment by AhoyLemon** [comment]
Yup. It came through. I'll give you access to the spreadsheet.

**Comment by AhoyLemon** [comment]
I guess this can be closed.
