### ISSUE TITLE
Simplified room code

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#29]
We were talking about a room shortcode that was 4 characters long, case-independent.

**Comment by AnotherDole** [comment]
Done in the Redis branch.

I want to say that I am disappointed that the library I am using specifically prevents words like SHIT and FUCK from appearing in the ID.

Leaving this open in case you want to add another front-end component to use this.

**Comment by AhoyLemon** [comment]
Oh, that *is* disappointing! Is it overridable? Can it go completely the other direction, where it first sees if there's a swear word available and then if there's not gives you a random id?

I'm kidding. Mostly.

**Comment by AhoyLemon** [comment]
Okay, I'm gonna just try an option here where you can also give somebody a room code. Might take a couple of incarnations.

**Comment by AhoyLemon** [comment]
[f26a382] has my current idea on this.

**Comment by AhoyLemon** [comment]
Works great. I just need to tweak the lobby view to display both join options now (the URL as well as just the room code)

**Comment by AhoyLemon** [comment]
Whoops.

**Comment by AhoyLemon** [comment]
Okay, this one handles the pause interface as well as the create/join interface. I removed the IDs and instead made `data-holds` attributes that are what the IDs used to be. Populated those in `sockets.js` and I'm like 95% confident this is right.

That said, I want to toss it over to you for a quick sec just to verify, please close if it looks right to you.

**Comment by AnotherDole** [comment]
Looks right to me.
