### ISSUE TITLE
post-vote screen

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#3]
There needs to be more one screen after the vote (before the player list) that will show what happened that round. It should connect players with statements, and should also show the points earned that round.As a reference, here's the post-round shot from drawful.
![scores assigned, round info displayed](http://i.imgur.com/T8KKhv2.jpg)

**Comment by AhoyLemon** [comment]
Working on an idea for this now. Concept is to add a `.revealed` class to the voting booth, which will demonstrate what player said what.

After the last player hits "Submit Votes", it will also show the score changes from that round. That part is gonna be trickier.

**Comment by AhoyLemon** [comment]
Nearly have this idea flushed out. I think the trickiest part to this is gonna be knowing that the screen is relevant to display, but only keeping it up for the appropriate amount of time.

**Comment by AhoyLemon** [comment]
Okay, so I *think* I have a system here that I like.
* The voting booth now has a `<cite>` element that holds player names, which is hidden by default.
* When the "Submit Votes" button is hit, it adds the `.revealed` class to `#VotingBooth`. This changes a number of things to the layout, most importantly showing all the `<cite>` elements so players can see who got what card.
* There's also a new element called `#WaitingAtBoothBecause` which is seen after you hit the Submit Votes button and should tell you why you're still looking at this screen.

Now the slightly tricker part...
I also have this layout in the voting booth:
```
<div class="player-score">
  <span class="inner" id="ScoreChange6"></span>
</div>
```
My idea here is that each of these `#ScoreChange` elements would get populated by the system ones all the votes are in and then the players would see the results simultanously.

My thinking at the moment is that this screen needs a timer. When the last player hits Submit Votes, it shows the scores to all players, and then `#WaitingAtBoothBecause` would say something like...
> Scores updated. New round in 5...

In any case, I wrote a temp function so that if you click `#WaitingAtBoothBecause`, it will toggle `.show-scores` on `#VotingBooth`, which is all that needs to happen for those bubbles to show up.

I hope that all makes sense. Gonna throw it back over to you, but let me know if something wasn't clear or you have a better idea.

Oh, PS: the `#ScoreChange` elements should only get populated if there's actually a change in score, so no 0's. The class is set up to remain hidden if it's empty.

**Comment by AnotherDole** [comment]
It doesn't seem like there is a way for a player to see the change to their own score.

**Comment by AhoyLemon** [comment]
Ooh, that's a super good point! I hadn't considered that.

Okay, here's my thought. I'm gonna try adding markup like this, (just above `<tbody id="VotingOptions">`)
```
<thead>
  <tr>
    <td class="votebutton></td>
    <td>
      <blockquote id="MyQuote"></blockquote>
      <cite><span id="MyCite"></span></cite>
    </td>
    <td class="votebutton">
      <div class="player-score">
        <span class="inner" id="MyScoreChange"></span>
      </div>
    </td>
  </tr>
</thead>
```

I'll hide that whole `<thead>` element by default, and then display it if `#VotingBooth` has the `.has-score` class.

**Comment by AhoyLemon** [comment]
Okay got that in there exactly as described. I have some dummy data in there just to test it.

**Comment by AnotherDole** [comment]
I think this is correct. 7 seconds is totally arbitrary, change it to whatever.

**Comment by AhoyLemon** [comment]
First try:
![this one is hard](http://hirelemon.com/junk/hard1.svg)

**Comment by AhoyLemon** [comment]
Is it possible to have it spit out nothing if the change is 0?

**Comment by AnotherDole** [comment]
Just to make sure, you mean that rather than showing a bubble with +0, it shouldn't show the bubble at all?

**Comment by AhoyLemon** [comment]
Right. The blue circle is triggered on .player-score .inner:not(:empty), so the bubble shouldn't show if the span is empty. But if you want to make the actual span display conditional, that works too.

As a note on the `:empty`, pseudoclass...
```
<span class="whatever"></span>
```
^-- That triggers as `:empty
```
<span class="whatever">
</span>
```
^-- that doesn't.

So the span can't have any whitespace in it.

**Comment by AnotherDole** [comment]
Should be fixed now.

**Comment by AhoyLemon** [comment]
Sure is! I'm closing this.
