### ISSUE TITLE
Mobile - tapping vote buttons has poor hitbox

### ISSUE THREAD

**Issue by samuwen** [AnotherDole/wrongest#32]
It takes a few taps to ensure you're properly engaging the hitbox on the vote buttons sometimes.

I'm also grotesquely overweight

**Comment by AhoyLemon** [comment]
I'll look at it, fatty.

**Comment by AhoyLemon** [comment]
Yeah, that thumb-scaling thing was a leftover from the old `fa` icons. I got rid of the scaling entirely, so now the hitbox will never change, and will stay in its cell.

This will close the task once the redis branch gets merged into master.
