### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#36]
This is definitely something for the future, but I've been reading into manifest files and the beta release of [push notifications](http://updates.html5rocks.com/2015/03/push-notificatons-on-the-open-web) and I think there would be some value in having the game delivered over HTTPS.

On the other hand, there's no real reason to do that yet.

**Comment by r4v5** [comment]
Would something like a free cert from startssl work, or do you need EV?

**Comment by AhoyLemon** [comment]
I don't know the answer to that, but after looking at StartSSL.com, I think I'd rather pay namecheap the 9 bucks.

**Comment by r4v5** [comment]
Completely valid criticism, though getting a cert is something you really only have to do once.
