### ISSUE TITLE
Visual indication that a re-vote is needed

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#37]
If someone leaves the game during the voting phase, everyone still in the room needs to vote again Right now it just resets the voting screen for the remaining players. It might be good to be able to display a message explaining what happened.

**Comment by AhoyLemon** [comment]
Are you thinking something like a toast?

> Pablo Neruda left the game. everyone needs to vote again.

That'll come from the bottom screen, hover for a second, and then drift out? Is that the general idea?

**Comment by AnotherDole** [comment]
I didn't have anything specific in mind, but a toast would work. It just need to be made clear somehow that if someone leaves during a vote, everyone re-votes.

**Comment by AhoyLemon** [comment]
K, I'll whip something up with a temp message. You'll probably just need to add a class to something using js at the appropriate time.

**Comment by AhoyLemon** [comment]
Code for later...
```
$('#VoteToasts').append('<li class=info>Pablo Neruda left the game. Everyone has to vote again.</a>'); clearToast('vote');
```

**Comment by AhoyLemon** [comment]
Okay, I've built a toast structure inside of the voting booth, and modified the toast structure on the setup screen. Couple things..
* You can now send to a toast either by the id...
```
$('#VoteToasts').append('...');
````
or by the screen attribute.
```
$('ul.toasts[data-toast="vote"].append('...');
```

**Comment by AhoyLemon** [comment]
Making a better version of this.

**Comment by AhoyLemon** [comment]
Okay, so here's the new syntax for toasts...
```
makeToast(holder, type, msg);
```
* **holder:** the container. currently either `vote` or `setup`
* **type:** what type of message, mainly affects color. Can either be `alert`, `info` or `success`. At the moment, I'd like any vote toast to be `info`, just so the colors don't clash.
* **msg:** Content of the toast itself.

This function also handles the clearing, so just `makeToast` with those three variables should cover you. I set one up on line 49 of sockets.js - if there's others, you're gonna have to alter 'em.

**Comment by AnotherDole** [comment]
Looks good except that the space where the toasts go on the room setup screen blocks out the settings.

**Comment by AhoyLemon** [comment]
Gotcha. Should be cool now
