### ISSUE TITLE
Explore a statement teaser.

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#45]
From a previous conversation, look into a way to do the following.

If you're next up to defend (so, after the person before you starts their defense), you get a teaser of what your card will be, ex "Teenagers find it difficult to..."

Try a UI solution first, then go through the statements and see if there's a simple and effective way to mark up what each one should look like.

**Comment by AnotherDole** [comment]
For the syntax in the decks, I was thinking that you would place a | where
you want the split to be. For the teaser it would be replaced by ... and
for the full statement it would be replaced by a space.

**Comment by AhoyLemon** [comment]
I think it might need to be wrapped in something? Just because I think there might be situations where you'd want your teaser to start after the first word. Like maybe...

> Dogs { are the most venomous animal in the world.}

> Licking { duct tape will improve} your vision.

> { Cocaine improves } heart function when taken in moderation.

Something like that? I dunno.

**Comment by AnotherDole** [comment]
Oh, I had only thought about the first example there. But yeah, that would
work. Obviously we'd just have to choose characters that aren't going to
appear in any quotes.

**Comment by AhoyLemon** [comment]
Well, I thought it would be safe to try this out in CSS, so here's what I got.

An `li` in `.player-order` can now get a class of `on-deck`.
If an li has `.on-deck`, it'll display the `.player-teaser` child. Here's what I'm thinking for markup.

```
<li class="on-deck">
  <span class="player-name"></span>
  <span class="player-score"></span>
  <span class="player-tease">Pouring sugar on a turtle will...</span>
</li>
```

The CSS will prepend/append quotes, but it'll still need to have the ellipses in the appropriate place(s)

**Comment by AhoyLemon** [comment]
And I *think* curly brackets make sense? It's pretty unlikely that they'd be used in a quote, whereas square brackets or pipes could be.

**Comment by AnotherDole** [comment]
I'm going to work on this a little in a branch

**Comment by AnotherDole** [comment]
Just pushed the "teasers" branch which contains my first attempt at this. Make sure to pick the miscellaneous deck if you try it.  I think the HTML is right but it's not displaying that well so maybe not.

**Comment by AhoyLemon** [comment]
Cool, I'll probably look at this tonight.

**Comment by AhoyLemon** [comment]
I think I really, really like this system.

Just committed (on the teaser branch) a couple fixes to the CSS, should display right.

1. `on-deck` doesn't get removed after your turn is over.
2. I was actually imagining that `on-deck` would happen at the same time as `active` happens for the player above, but I think your way is probably better.

**Comment by AhoyLemon** [comment]
07b08d9

**Comment by AnotherDole** [comment]
Awesome, thanks for doing that. Just pushed some fixes. One thing that might be nice is that when you see the full statement, the words that were hidden before could be in a different color or something to make them stand out.

**Comment by AhoyLemon** [comment]
Hmmm, okay. Let me try something like that out...

**Comment by AhoyLemon** [comment]
Okay, got a class in there. I'm genuinely not sure if I like it or not, I'd love you to have a look at it and see what you think.
The plan here is to just wrap the part in curly brackets with `<span class="revealed">` So....
```
<blockquote id="statementDiv">
  A cat's vertically-split pupils allow it to 
  <span class="revealed">see ghosts, but only the ghosts of</span>
  other cats.
</blockquote>
```
Currently renders it in a darker pink.

I dunno, gimmie yer opinion.

**Comment by AnotherDole** [comment]
I think it's helpful if the hidden part is in the middle of the statement
but it's not necessary if the hidden part is at the beginning or the end. I
could make it so it only applies if the hidden part was in the middle but
then it would be inconsistent.

I don't think it's essential so if you don't like it or think it's
necessary then it doesn't need to stay. My thought process was just that if
you were reading the teaser and were trying to think of what could go in
the hidden part, it would be helpful to be able to see it immediately.

**Comment by AhoyLemon** [comment]
I think the struggle I'm having with it is just in knowing if the mechanic is right, because it's different than what I'm used to right now. If people are genuinely playing teasers, if we can assume that everyone's reading the teaser statement before they see their actual statement, then it's working perfectly and it's aligned correctly.

If that's not the case, it's just sort of odd to see part of the statement in pink.

I think I like it? But in any case, I think the structure should stay like that, because it would be perfectly easy to swap out different colors or UI ideas for the hidden statements.

**Comment by AnotherDole** [comment]
Well, the branch is pretty much done. Do you want to merge it in for 0.1 or wait until people have played with the original a little?

**Comment by AhoyLemon** [comment]
Yeah, I think so. The merge will be safe anyway, if we have a last minute regret, it'll be really easy to just not show that stuff with CSS anyway

**Comment by AnotherDole** [comment]
Alright, it's in.

**Comment by AhoyLemon** [comment]
Did two test games (with myself) just now. I'm warming up to it, I think it'll makes the game more interesting.

**Comment by AnotherDole** [comment]
Actually, looking at it now, I'm not sure I like the different color when you see the full statement. I'm leaning towards taking it out and adding it back in if people complain, but I don't feel strongly either way.

**Comment by AhoyLemon** [comment]
Darkened and desaturated the color. Any better? Or should we just go back to black?

**Comment by AnotherDole** [comment]
I think it's fine for now.
