### ISSUE TITLE
Wrongest twitter

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#47]
Just an idea, but I think it might be worth setting up a Twitter account specifically for the wrongest words. I can make an IFFT that'll auto-tweet GitHub commits.

**Comment by AhoyLemon** [comment]
https://twitter.com/wrongestwords

**Comment by AhoyLemon** [comment]
Github commit tweet is set up and should work (I'll know soon). Let me know if you want access to this account.

**Comment by AhoyLemon** [comment]
Yup, it works.
https://twitter.com/wrongestwords

**Comment by AnotherDole** [comment]
I'm not sure how interesting the commit log is, but alright.

**Comment by AhoyLemon** [comment]
Yeah, it's more of a science experiment at the moment. I think hopefully I'll be able to cater it to tweet out relevant commits only when it's appropriate.
