### ISSUE TITLE
wrongest.net domain

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#5]
Set up [wrongest.net](http://wrongest.net) to redirect to [wrongestwords1-dole.rhcloud.com](http://wrongestwords1-dole.rhcloud.com). CNAME instructions are [here](https://developers.openshift.com/en/managing-domains-ssl.html).

**Comment by AhoyLemon** [comment]
Edited the @ and CNAME records, I *think* I did it right. Have to check back in a couple hours after the domain propagates.

**Comment by AnotherDole** [comment]
It's working for me. I just need to adjust some things on the server so everything connects correctly.

**Comment by AnotherDole** [comment]
It should be working now. Give it a try.

**Comment by AnotherDole** [comment]
Sorry, I'm not meaning to spam this but I noticed one more thing.

www.wrongest.net works correctly, but wrongest.net redirects to http://wrongestwords1-dole.rhcloud.com. (notice the . at the end) which works but is not ideal.

**Comment by AhoyLemon** [comment]
Yeah, I'm struggling to get this set up correctly. The www domain is working as it should, but without the www it's fucked up. This is gonna take some research.

**Comment by AhoyLemon** [comment]
Okay, this is... not the best case scenario, but...
I changed the @ record to redirect to www.wrongest.net, everything's working.

In a perfect world, I wouldn't want to have www. in the address at all, but I can live with this.

**Comment by AhoyLemon** [comment]
Sticking with www for now, closing task.
