### ISSUE TITLE
Simplify joining via link

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#50]
For consistency and simplicity, I'm about to push a commit so that visiting a link with the room code in it takes you to the join room screen available from the main menu and fills in the room code input for you. I commented out the HTML for the old join screen. Delete that section and close this issue if that's okay with you.

**Comment by AhoyLemon** [comment]
Awesome. Wanna tweak the focus on this, but yes.

**Comment by AhoyLemon** [comment]
ab185a0
