### ISSUE TITLE
GA event on game end.

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#55]
The game should send an analytic event when a game ends with the notice that the game has ended. But it should only happen once. I think the cleanest way to figure that out is to only have the game leader send back the event.

Possible data to send at this point:

* Wrongest Words of the game
* How many players there were at the end
* Top score
* How long the game took? That might be complicated.

**Comment by AnotherDole** [comment]
Which of these to you want to track via GA and which do you need to track via the server?

Another thing I thought might be interesting to track is the number of games completed per room.

**Comment by AhoyLemon** [comment]
I guess it's about what's easiest to implement and what's easiest to retrieve. GA events are pretty easy to make (basically just a single line of code with the variables that you want to send), but a little bit complicated to do anything with. Let me sketch out something in the end game function real quick, although I'm having a difficult time checking for if you're the leader or not, so I might need help there.

**Comment by AnotherDole** [comment]
You could just do 
`if(meDealer)`{}
in the gameover event to only send one per room.

**Comment by AhoyLemon** [comment]
Ooh, I didn't see that. Okay, let me try that.
