### ISSUE TITLE
Change URL for create game and join game

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#56]
Super small thing, but something I noticed.

When looking at real time data (or any data for that matter), you can see clusters of players grouped by room code, which is terrific, but that data won't include the player who created the game or any player who joined by using room code rather than URL.

In both of those cases, I'd love to try a soft URL change (using `history.pushState`) so that the URL will indicate what everyone's room code is.

Again, totally a small thing, but probably worth doing.

**Comment by AnotherDole** [comment]
I updated the server this morning so you can check if this is working.

**Comment by AhoyLemon** [comment]
Yeah, the data looks like I want it to. Closing.
