### ISSUE TITLE
appify with Cordova or PhoneGap

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#68]
I like the idea of it remaining a webapp and wouldn't want that to stop being the case, but there's definite value in having an app which prevents a phone from going to sleep, since the impersistent connections have been a weird struggle.

**Comment by AnotherDole** [comment]
http://socket.io/socket-io-with-apache-cordova/

It looks like socket.io already plays well with Cordova.

**Comment by AhoyLemon** [comment]
K, as time avails itself, I'm gonna try to put together a test Android build of this thing.
