### ISSUE TITLE
Reconnecting dropped players

### ISSUE THREAD

**Issue by AhoyLemon** [AnotherDole/wrongest#69]
Based on an email conversation with @AnotherDole 

> I'm assuming the dealer would be the one to decide whether or not to kick the disconnected player, but what should happen if the dealer gets disconnected?

I think it wouldn't be based on dealer but based on game host (that is, the person who started the game), who we can still assume/hope is the most reliable person in the game.

If that host gets disconnected, then it would have to switch hosts in a way that was somehow communicated to the audience 

so, in my scenario, Carlos is the host and Jenny is the current dealer. Carlos just read as dropped.

```
1. Jenny
2. Hans
3. Carlos (host, dropped)
4. Bill
5. Jenny's Sister
```

If Carlos is coming back as dropped, we want to leave his slot open but we'll need to switch the "host" job to somebody else (Bill, I guess). Bill's then got the ability to boot out Carlos, but it's also possible for Carlos to come back to his old slot (though Bill would remain the host).

> What happens if multiple people get disconnected? Should there be an option for each individual person or a single option to kick everyone who has been disconnected?

I think the indicator that a person has been disconnected should be present immediately, but you'd only need to take action on that if and when it becomes game-breaking. For example, using the list above, Carlos has listed as dropped, but it's Jenny's turn currently. So that means that Carlos gets an indicator on his player order box ([something like this?](https://thenounproject.com/search/?q=disconnected)) but that's just the extent of it. Once it becomes Carlos' turn, now somebody has to make a decision. It's Carlos' turn but he's reading as dropped. Should we wait for him to come back or should we kill him and move on?

There would be two possible times this question is asked: When it's time for a player to defend a statement, and when everyone has registered a vote except for the players who are marked as dropped.

> What happens if someone gets disconnected while they are defending their statement and they reconnect? Is their turn over or do they get another 30 seconds?

Definitely not the latter. As long as you've seen your statement, you've had the ability say things out loud, although maybe the experince wasn't perfect. So if you come back and your turn got nuked (in my mind, the clock ticks as normal), that feel more like a user error or an act of god, or just the way games work sometimes. If something weird happen, me and my friends try to work through it, but then Carlos reconnects and now it's like "Oh, Carlos is back, let's have a do-over", that's gonna feel more like "This game did something wrong."

**Comment by AnotherDole** [comment]
That all makes sense. If you can add the front end components for it I'm pretty sure I can make it work.

**Comment by AhoyLemon** [comment]
Yeah, I can do all the front end parts to it

**Comment by AhoyLemon** [comment]
How do you think we could start with this?

**Comment by AnotherDole** [comment]
I think you just need to add the front end components for this and I can take it from there. It looks like the only things needed are: 
1. Something for the player list to indicate that a player has disconnected
2. A way to pop up a message on the player list and voting screens to ask if a player should be kicked out

**Comment by AhoyLemon** [comment]
K.  I'll work on a front end structure for this when I'm back in Minneapolis
