### ISSUE TITLE
Merging Redis branch into Master

### ISSUE THREAD

**Issue by AnotherDole** [AnotherDole/wrongest#8]
Right now the app doesn't scale. Everything is stored in memory on one server and if that server reaches its maximum capacity somehow then it would just stop accepting new requests. The way to make it scale seamlessly across multiple servers is to store the game data on a shared database that all of the servers can access. To solve that, I've been working on a branch that uses Redis to store the game data. It's not finished yet but it is working pretty well.

The only change from your perspective would be that to test things locally, you would need to download Redis (it is surprisingly small) and run it before running the server.

Maybe the game will never reach the point where this is necessary, but if it does it would be nice to be prepared. I wasn't planning on merging it in so soon, but I think some of the proposed features require some changes to how the server works and I would prefer to not have to maintain two separate versions of the server.

**Comment by AhoyLemon** [comment]
Rad. I've totally never heard of redis, but I'm interested.

**Comment by AnotherDole** [comment]
Okay, I think the Redis branch is ready.

In order to run the server locally, you would also need to be running Redis locally. I don't know what OS you're running, but if it's Windows, you can download it [here.](https://github.com/MSOpenTech/redis/releases) Download the .zip file, unzip it somewhere, and then run redis-server.exe. When you're done, just close that window.

Let me know if this is okay.
